[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "cracker-sdk"
version = "0.1.0"
description = "Minimal local Firecracker SDK boilerplate"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

 

[tool.setuptools.packages.find]
where = ["src"]
 